### ISSUE TITLE
[CB-HD-ACCREQ] Access Request 

### ISSUE THREAD

**Issue by AvishkaSooriyapperuma** [Satriaana/HelpDesk#14]
Platform: Azure DevOps

The account I gave to register in dev.azure.com/satriaana consists of the previous student mail and now it is changed. So now I can't access the site and I can't refer the site. Can someone help me with that?

Access Level:

Business justification: 

Do you have your team lead's approval? If yes, please mention your team lead:

Any references:

**Comment by BuddhikaD** [comment]
Fixed and done now he can access the board
